export const SELECT_GROUP = 'SELECT_GROUP',
  CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS',
  GET_GROUP_USERS_SUCCESS = 'GET_GROUP_USERS_SUCCESS',
  ADD_USER_TO_GROUP_SUCCESS = 'ADD_USER_TO_GROUP_SUCCESS',
  REMOVE_USER_FROM_GROUP_SUCCESS = 'REMOVE_USER_FROM_GROUP_SUCCESS',
  GET_GROUP_MESSAGES_SUCCESS = 'GET_GROUP_MESSAGES_SUCCESS',
  ADD_MESSAGE_TO_GROUP_SUCCESS = 'ADD_MESSAGE_TO_GROUP_SUCCESS';
