export const AUTHENTICATION_SUCCESS = 'AUTH_SUCCESS',
  LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS',
  GET_USER_SUCCESS = 'GET_USER_SUCCESS',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS',
  SELECT_USER = 'SELECT_USER',
  CLEAR_SELECTED_USER = 'CLEAR_SELECTED_USER',
  FETCH_USER_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS';
